# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://om-consultant.com
title: OM Consultant
email: info@om-consultant.com
author: Shyamal Ghosh
description: Shyamal Ghosh, OM Consultant
copyright: Copyright &copy; 2015 OM Consultant. All Rights Reserved.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/om-consulting
  - title: twitter
    url: https://github.com/shyamalghosh/om-consultant.com
  - title: linkedin
    url: https://linkedin.com/om-consultant/
