# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://om-consultant.com
baseurl: #

title: OM Consulting
subTitle: Joint Ventures and Liaison Service
email: info@om-consultant.com
author: Shyamal Ghosh

description:
  en: Shyamal Ghosh, Om Consulting
  de: Shyamal Ghosh, Om Consulting
copyright:
  en: Copyright &copy; 2015 OM Consultant. All Rights Reserved.
  de: Copyright &copy; 2015 OM Consultant. Alle Rechte vorbehalten.


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/om-consulting
  - title: twitter
    url: https://github.com/shyamalghosh/om-consultant.com
  - title: linkedin
    url: https://linkedin.com/om-consultant/

nav-links:
  home:
    en: Home
    de: Startseite
  about:
    en: About
    de: Ãœber uns
  services:
    en: Services
    de: Leistungen
  team:
    en: Team
    de: Mannschaft
  contact:
    en: Contact
    de: Kontakt
